# Generated by Django 5.1.2 on 2024-10-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_member_registered_monthperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthperiod',
            name='month',
            field=models.CharField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')]),
        ),
    ]
