# Generated by Django 5.1.2 on 2024-10-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_member_overdue_balance_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='registration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
