# Generated by Django 5.1.2 on 2024-10-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_member_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='membersessionlink',
            name='did_long',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membersessionlink',
            name='did_short',
            field=models.BooleanField(default=False),
        ),
    ]
