# Generated by Django 5.1.2 on 2024-10-18 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_membersessionlink_did_long_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membersessionlink',
            unique_together={('member', 'session')},
        ),
    ]
