# Generated by Django 5.1.2 on 2024-10-18 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_membersessionlink_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('member', 'month_period')},
        ),
    ]
