# Generated by Django 5.1.2 on 2024-10-29 21:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_payment_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount_due',
            new_name='month_amount_due',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='no_sessions',
            new_name='month_no_sessions',
        ),
        migrations.AddField(
            model_name='payment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='date_paid',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
