# Generated by Django 5.1.2 on 2024-10-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_rename_amount_due_payment_month_amount_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthperiod',
            name='academic_year',
            field=models.CharField(default='none'),
            preserve_default=False,
        ),
    ]
