# Generated by Django 5.1.2 on 2024-11-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_messagetemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagetemplate',
            options={'verbose_name': 'Message Template', 'verbose_name_plural': 'Message Templates'},
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='short_title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='type',
            field=models.CharField(choices=[('current_month', 'Member Attended Sessions in Month'), ('current_month_overdue', 'Member Attended Sessions in Month + Overdue'), ('no_sessions', 'Member Did Not Attend Sessions in Month'), ('no_sessions_overdue', 'Member Did Not Attend Sessions in Month + Overdue')], default='current_month', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
