# Generated by Django 5.1.2 on 2024-11-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_alter_messagetemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='type',
            field=models.CharField(choices=[('current_month', 'Member Attended Sessions in Month'), ('current_month_overdue', 'Member Attended Sessions in Month + Overdue'), ('no_sessions', 'Member Did Not Attend Sessions in Month'), ('no_sessions_overdue', 'Member Did Not Attend Sessions in Month + Overdue')], max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='messagetemplate',
            unique_together={('month_period', 'type')},
        ),
    ]
