# Generated by Django 5.1.2 on 2024-11-03 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_alter_messagetemplate_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('current_month', 'Member Attended Sessions in Month'), ('current_month_overdue', 'Member Attended Sessions in Month + Overdue'), ('no_sessions', 'Member Did Not Attend Sessions in Month'), ('no_sessions_overdue', 'Member Did Not Attend Sessions in Month + Overdue'), ('other', 'Other')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('default_body', models.TextField()),
            ],
            options={
                'verbose_name': 'Message Types',
            },
        ),
        migrations.AlterUniqueTogether(
            name='messagetemplate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='message_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attendance.messagetype'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='type',
        ),
    ]
