# Generated by Django 5.1.2 on 2024-11-04 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_messagetype_alter_messagetemplate_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagetype',
            options={'verbose_name': 'Message Type', 'verbose_name_plural': 'Message Types'},
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('date', 'month_period')},
        ),
    ]
